apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-db
  template:
    metadata:
      labels:
        app: kc-db
    spec:
      containers:
      - name: kc-db
        image: postgres
        env:
          - name: POSTGRES_USER
            value: 'keycloak'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KC_DB_PASSWORD
          - name: PGDATA
            value: /var/lib/postgresql/data/keycloak
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: kc-db-storage
            mountPath: /var/lib/postgresql/data/
            readOnly: false
      volumes:
        - name: kc-db-storage
          persistentVolumeClaim:
            claimName: kc-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kc-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres" 
