apiVersion: v1
kind: Service
metadata:
  name: kc-db
spec:
  selector:
    app: kc-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-db
  template:
    metadata:
      labels:
        app: kc-db
    spec:
      containers:
      - name: kc-db
        image: postgres
        env:
          - name: POSTGRES_USER
            value: 'keycloak'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KC_DB_PASSWORD
          - name: PGDATA
            value: /var/lib/postgresql/data/keycloak
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: kc-db-storage
            mountPath: /var/lib/postgresql/data/
            readOnly: false
#          - name: postgres-hba-config
#            mountPath: /var/lib/postgresql/data/pg_hba.conf
#            subPath: pg_hba.conf
#            readOnly: false
      volumes:
        - name: kc-db-storage
          persistentVolumeClaim:
            claimName: kc-db-pvc
#        - name: postgres-hba-config
#          configMap:
#            name: postgres-hba-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kc-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-hba-config
data:
  pg_hba.conf: |
    # Unix sockets
    local all all trust
    local all all peer
    # IPv4 local connections:
    host  all all 127.0.0.1/32      md5
    host  all all 102.37.124.150/32 md5
    host  all all 102.37.217.33/32  md5
    # IPv6 local connections:
    host  all all ::1/128          md5
