apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      restartPolicy: Never
      containers:
        - args: ['start']
          env:
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_URL
              value: 'jdbc:postgresql://kc-db/keycloak'
            - name: KC_DB_USERNAME
              value: 'keycloak'
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_DB_PASSWORD
            - name: KC_HOSTNAME_URL
              value: 'https://auth.respotify.org'
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_STRICT_HOSTNAME
              value: 'false'
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KEYCLOAK_ADMIN
              value: 'admin'
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_PASSWORD
            - name: KC_PROXY
              value: 'edge'
          image: quay.io/keycloak/keycloak:24.0.1
          name: keycloak
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: kc-db-storage
              mountPath: /opt/jboss/keycloak/standalone/data
      restartPolicy: Always
      volumes:
        - name: kc-db-storage
          persistentVolumeClaim:
            claimName: kc-db-pvc
