apiVersion: v1
kind: ConfigMap
metadata:
  name: song-service-configmap
data:
  DB_NAME: postgres
  DB_USERNAME: postgres
  init.sql: |
    START TRANSACTION;

    CREATE TABLE "Songs" (
        "Id" uuid NOT NULL,
        "Title" text NOT NULL,
        "Artist" text NOT NULL,
        "ImageLink" text NOT NULL,
        "AudioLink" text NOT NULL,
        CONSTRAINT "PK_Songs" PRIMARY KEY ("Id")
    );

    COMMIT;


