apiVersion: v1
kind: Service
metadata:
  name: song-db
spec:
  selector:
    app: song-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: song-db
  name: song-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: song-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: song-service-secrets
                  key: DB_PASSWORD
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg_isready --username=postgres --dbname=postgres
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: song-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: song-db-volume
      restartPolicy: Always
      volumes:
        - name: song-db-volume
          persistentVolumeClaim:
            claimName: song-db-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: song-db-volume
  name: song-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
