apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGINS
              value: 'https://respotify.org'
            - name: KC_JWKS_URL
              value: 'http://keycloak:8080/realms/respotify/protocol/openid-connect/certs'
            - name: DB_HOST
              value: 'song-db'
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: song-service-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: song-service-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: song-service-configmap
                  key: DB_NAME
          image: respotify.azurecr.io/song-service
          name: song-service
      restartPolicy: Always
