apiVersion: v1
kind: Service
metadata:
  name: song
spec:
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: song-db
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: song-service-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: song-service-secrets
                  key: DB_PASSWORD
          image: respotify.azurecr.io/song-service
          name: song-service
      restartPolicy: Always
